# Generated by .github/workflows/homebrew-formula.yml on every
# release; do not hand-edit the version or sha256 values.
class Ejson < Formula
  desc "Manage encrypted secrets using public key encryption"
  homepage "https://github.com/runlevel5/ejson-rs"
  version "1.0.5"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/runlevel5/ejson-rs/releases/download/v#{version}/ejson-#{version}-aarch64-apple-darwin.tar.xz"
      sha256 "8c1523fb48dd63bb6bc26ed80ce752bee6c6e6d48079c55cb5e3b276036780ba"
    end
    on_intel do
      url "https://github.com/runlevel5/ejson-rs/releases/download/v#{version}/ejson-#{version}-x86_64-apple-darwin.tar.xz"
      sha256 "7bbf41336e557b8d2254d493b0be718f915931a9bc88f0ebe739a22096aa838c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/runlevel5/ejson-rs/releases/download/v#{version}/ejson-#{version}-aarch64-unknown-linux-gnu.tar.xz"
      sha256 "2663282678665466baa7a1d1fd9778b89fcc92cd546d9165c26a136530cc05e0"
    end
    on_intel do
      url "https://github.com/runlevel5/ejson-rs/releases/download/v#{version}/ejson-#{version}-x86_64-unknown-linux-gnu.tar.xz"
      sha256 "14e8ff7f39140b6318d3fa4c8d835ff15c9c073d1d54ad4c0696c9aa8b8de2ec"
    end
  end

  def install
    bin.install "ejson"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ejson --version")
  end
end
