# Generated by .github/workflows/homebrew-formula.yml on every
# release; do not hand-edit the version or sha256 values.
class Ejson < Formula
  desc "Manage encrypted secrets using public key encryption"
  homepage "https://github.com/runlevel5/ejson-rs"
  version "1.0.6"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/runlevel5/ejson-rs/releases/download/v#{version}/ejson-#{version}-aarch64-apple-darwin.tar.xz"
      sha256 "bc84a2a9704d86161e15e335fa965ad1f39d0fd1ff5948883bf16d63b1ed7f8e"
    end
    on_intel do
      url "https://github.com/runlevel5/ejson-rs/releases/download/v#{version}/ejson-#{version}-x86_64-apple-darwin.tar.xz"
      sha256 "498369e8945927b33f2586317fbfe5101e1f5bdf1033f3666ec4045907004697"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/runlevel5/ejson-rs/releases/download/v#{version}/ejson-#{version}-aarch64-unknown-linux-gnu.tar.xz"
      sha256 "b0cabda44d73137972d5a90eacdaaa0fa3e74a7ba63c84119037586b7431cb8c"
    end
    on_intel do
      url "https://github.com/runlevel5/ejson-rs/releases/download/v#{version}/ejson-#{version}-x86_64-unknown-linux-gnu.tar.xz"
      sha256 "f52f34643754849e6bf8101dea58859adf7a2330b66bbcd58ccff2c32967b1e3"
    end
  end

  def install
    bin.install "ejson"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ejson --version")
  end
end
