# Generated by .github/workflows/homebrew-formula.yml on every
# release; do not hand-edit the version or sha256 values.
class Ejson < Formula
  desc "Manage encrypted secrets using public key encryption"
  homepage "https://github.com/runlevel5/ejson-rs"
  version "1.0.3"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/runlevel5/ejson-rs/releases/download/v#{version}/ejson-#{version}-aarch64-apple-darwin.tar.xz"
      sha256 "4849f5ca5d55fddb0c214a224e5bad2e13263615384829d75c6ad5a45a779a7c"
    end
    on_intel do
      url "https://github.com/runlevel5/ejson-rs/releases/download/v#{version}/ejson-#{version}-x86_64-apple-darwin.tar.xz"
      sha256 "58b0201f11ea7ecd1433501c15dbf42a7610f39c61a63e6fc799dbd5015925f7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/runlevel5/ejson-rs/releases/download/v#{version}/ejson-#{version}-aarch64-unknown-linux-gnu.tar.xz"
      sha256 "5fac111fcc3b92fd51a130741628fab1c14ed2235f18827d65bba27ca95732ee"
    end
    on_intel do
      url "https://github.com/runlevel5/ejson-rs/releases/download/v#{version}/ejson-#{version}-x86_64-unknown-linux-gnu.tar.xz"
      sha256 "4b6072ed1ba121c62e141e0128c5f1bd38cf88ddbf7f477464c28d7b36d7d7bc"
    end
  end

  def install
    bin.install "ejson"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ejson --version")
  end
end
